### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by amanzainal** [bitst0rm-pub/Formatter#37]
Hi, I'm having issues setting up the Formatter.
I'm trying to set it up to auto-format my Python code. I've installed the YAPF plugin but the Formatter tab isn't showing any options. With debug set to true, this is the console output:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 478, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 619, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "...\Roaming\Sublime Text 3\Packages\Formatter\main.py", line 694, in on_activated
AttributeError: 'module' object has no attribute 'config'

How do I resolve this?

**Comment by bitst0rm** [comment]
Hi,
please look at the beginning of the log for the line:
`Plugin initialization succeeded` or
`Plugin initialization failed` and maybe other error messages.

**Comment by amanzainal** [comment]
Hi! Thanks for the prompt reply. I managed to fix the error by running Sublime Text 3 as administrator. However, this was not an issue previously, and I'm not sure why I have to run it as admin now:

reloading plugin Formatter.main
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 127, in reload_plugin
    load_module(m)
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 156, in load_module
    obj = t()
  File "C:\Users\Aftershock\AppData\Roaming\Sublime Text 3\Packages\Formatter\main.py", line 664, in __init__
    self.session_manager = supplementer.SessionManager(max_database_records=600)
  File "C:\Users\Aftershock\AppData\Roaming\Sublime Text 3\Packages\Formatter\core\supplementer.py", line 98, in __init__
    os.makedirs(common.dirname(SESSION_FILE), exist_ok=True)
  File "./python3.3/os.py", line 262, in makedirs
PermissionError: [WinError 5] Access is denied: '..\\Local'

Let me know if there's another workaround or if I need to keep running as admin.

**Comment by bitst0rm** [comment]
Hi @amanzainal again,

Formatter requires permission to read and write config files in the following locations:
1. `C:\Users\xxx\AppData\Roaming\Sublime Text 3\Packages\Formatter\ ` - Config files of Formatter itself.
2. `C:\Users\xxx\AppData\Roaming\Sublime Text 3\Packages\User\` - Quick Options persistent config file
3. `C:\Users\xxx\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\` - Third-party references config files
4. `C:\Users\xxx\AppData\Roaming\Sublime Text 3\Local\` - Session file (option: "remember_session": true,)

If it doesn't have access to these locations, you may encounter the following error:
`Plugin initialization failed`, followed by
`AttributeError: 'module' object has no attribute 'config'` (as mentioned in your initial post). Caused by location Nr. 1
`PermissionError: [WinError 5] Access is denied: '..\Local'` (as mentioned in your 2. post). Caused by location Nr. 4

Additionally, the upcoming version will introduce a new feature that allows users to run code interactively REPL (Read - Evaluate - Print - Loop) in the shell within Sublime Text. The related file for this feature will be located in:
`C:\Users\xxx\AppData\Roaming\Sublime Text 3\Local\`

Sum up: It is not possible to run Formatter without reading and writing config files and i do not know another approach to achieve this.

In very old previous versions, there was no need to write config files except for those within `formatter.assets`. However, in the newer versions, Formatter has become more modular and complex giving users more freedom and flexibility. The configuration management is now entirely automatic. This is why it need read and write, but everything is **strictly** limited to `AppData\Roaming\Sublime Text 3\ ` and working absolutely offline. These are two elementary developing rules in the first day.

**Comment by amanzainal** [comment]
I see, that makes sense. Either way, it might be my own local permission settings messing things up. For now, the issue has been resolved by running ST3 as administrator.

Thank you!
