### ISSUE TITLE
Prettier Config Always Loads Default

### ISSUE THREAD

**Issue by wkirby** [bitst0rm-pub/Formatter#42]
This is an issue that extends to other formatters as well, but is particularly problematic for Prettier. Prettier features several auto-discovered config filenames (https://prettier.io/docs/en/configuration).

https://github.com/bitst0rm-pub/Formatter/issues/41 added support for per-project Prettier discovery, but the way that `get_config_path` in `core/common.py` works, a single, system-wide config file is expected. If one is not defined, the built-in `prettier_rc.json` is loaded.

Current workaround is to override the entire `prettier` settings block with an empty dict, which logs a warning `Setting key "config_path" must be a non-empty dict`, but results in falling through to Prettier's auto-discovery for config files.

It would be good if out-of-the box, Prettier's config were setup to support the auto-discovery of config files on a per-project basis.

**Comment by bitst0rm** [comment]
I still do not get it, the #41 was about `get_executable()` not `get_config_path()`

As you said, by setting` "config_path"` to an empty dictionary:

`"config_path": {}`

then Formatter will **not** attempt to locate the user config file anymore. It results:
```
▋[Formatter](Thread-26:common.py#L397): [WARNING] Setting key "config_path" must be a non-empty dict: {}
▋[Formatter](Thread-26:common.py#L399): [WARNING] Vendor default config will be used instead if any.
```
`Vendor default config will be used instead if any.`: means Prettier is alone responsible for auto-discovering its config files according to your link [https://prettier.io/docs/en/configuration](https://prettier.io/docs/en/configuration). If no config file found, then Prettier uses hardcoded config in its code or what ever `Vendor default config` they are.  Formatter is out and has nothing to do anymore.

my test:
`"config_path": {}`
- project_a:
 |__ file_to_format.js
 |__`.prettierrc`.json ({"tabWidth": 22}) <-- Prettier owns this, not Formatter built-in (prettier`_rc`.json)

Result as expected: tabwith 22 chars + auto-discovery of config files on a per-project basis.

Btw, Formatter built-in `prettier_rc.json` is super powerful over all, but only get loaded in only 1 case, if:
```
"config_path": {
    "xxx": "/xxx/prettier_rc.json"
}
```
defined as a valid, existing and accessible path, otherwise vendor plugins are responsible to do all this.

----------
To the test above with this idea:
```
"config_path": {
    "xxx": "/xxx/prettier_rc.json"
}
```
The user config file can exist there so no need to repeatedly disable and enable it. Instead, on a per-project basis, you can add a control file such as .noformatter. This way, the vendor plugin will use its auto-discovery for config file when this control file is present: No need to repeatedly edit `"config_path"` to empty dict, is good so?
test for noformatter https://github.com/bitst0rm-pub/Formatter/commit/5776360f5fc7e2542bfd8231db0bda5dd59b9184 in branch [noformatter_wkirby](https://github.com/bitst0rm-pub/Formatter/tree/noformatter_wkirby)

**Comment by wkirby** [comment]
@bitst0rm If the recommendation is to set the `config_path = {}` that works. I think the disconnect is with the _default_ settings on a fresh install of formatter, formatting with `prettier` will default to the built-in prettier config instead of the project's prettier config.

**Comment by bitst0rm** [comment]
@wkirby 
> formatting with `prettier` will default to the built-in prettier config instead of the project's prettier config.

No, there is a check for a valid path that ensures `config_path = {}` path items are only applicable if the user explicitly chooses these path items over the project's config.
The next build release will contain the implementation to simplify process to use project's config in favor of `config_path`:
```
            // Path to the config file for each individual syntaxes.
            // Syntax keys must match those in the "syntaxes" option above.
            // A single config file can be used to assign to all syntaxes.
            // In this case, the key must be named: "default"
            // Formatter provides a set of default config files under
            // "formatter.assets/config" folder for your personal use.
            // Do not use the reference files with suffix '.master.' directly.
            // These files could be overwritten by any release updates.
            // Note: Options from this config file always have precedence over
            // the options from any local project (per-project config file).
            // To disable this option in favor of the local project config:
            // 1. Set the config path of this option to null, OR
            // 2. Use the Quick Options: Enable Project Config, OR
            // 3. Place an empty '.cfgignore' file inside the project root folder.
            // Formatter will start to search up the file tree until a
            // '.cfgignore' file is (or isn’t) found.
            "config_path": {}
```
