### ISSUE TITLE
php version get fail when php -v return 8.1.2-1ubuntu2.14

### ISSUE THREAD

**Issue by awebc** [bitst0rm-pub/Formatter#47]
[Formatter](formatter.py#L36): [DEBUG] Formatter ID: phpcsfixer
▋[Formatter](common.py#L317): [DEBUG] Global interpreter found: /usr/bin/php
▋[Formatter](main.py#L484): [ERROR] Error occurred: invalid version number '8.1.2-1ubuntu2.14'
  File "/home/yunsong/.config/sublime-text-3/Packages/Formatter/main.py", line 475, in run

Please fix it at :
version = string.splitlines()[0].split(' ')[1]

~/.config/sublime-text-3/Packages/Formatter/modules/formatter_phpcsfixer.py

**Comment by bitst0rm** [comment]
Hi @awebc 

Thank you for your bug report. You are the best, please more, if you found any bug.
I have removed the obsolete compatibility check completely.

The bug is fixed in the `master` branch.

I will release a new version within this week with this fix and
with an new feature (if test ok) to allow user `generic` add plugins without to write any modules.
This makes Formatter more flexible and powerful.
