### ISSUE TITLE
warning messages in console

### ISSUE THREAD

**Issue by asparc** [bitst0rm-pub/Formatter#49]
Hi!

I'm noticing a continuous stream of warning messages popping up in the Sublime console:
```
warning: mnemonic F not found in menu caption formatR
warning: mnemonic P not found in menu caption pgFormatter
```
These two messages appear each time when click in the Menu bar (the bar with File, Edit, Selection, Find, ...)

 I tried a fresh Sublime install with a fresh Formatter install, and can confirm that these warning messages are really caused by Formatter in default settings.

I'm using Linux.

Could you remove these warning messages?

**Comment by bitst0rm** [comment]
Hi @asparc 

Thank you for your bug report. Much appreciated!
I have mistakenly used the lower case instead of the capitalized one (formatR != FormatR) for the menu caption.

It has been fixed now in the `master` branch.

You can ignore this as it is just a minor cosmetic issue until the next release 1.3.0, scheduled for this week along with an new implementation: Text-to-Image working in the same way as Text-to-Text

Off-topic:
Assuming everything is working well as expected: The `"debug"` option in the settings includes a new flag named: `"status"` (minimal info). It only prints formatting results on the 3rd-party level instead of verbose on the Formatter level. Verbose output may contain excessive information for everyday use.

Lastly, I forgot to tell that you can omit the file extension to make the `"executable_path"` system-wide:
```
//   Basename can be with or without dot.extension as both variants are the same.
//   For example: "fiLe.exe" (Windows only), "fiLe" (Windows + Unix + Linux)
```
Update: I released 1.3.0 with this fix. Please just feel free to re-open it.

**Comment by asparc** [comment]
Hi @bitst0rm,

Thanks a lot for addressing my issue so very fast!!
And yes, I got everything working cross-platform, but the new extension omission feature could come in handy as well :-)

**Comment by bitst0rm** [comment]
Hi @asparc 
It is not useful for today but might be useful for tomorrow.
Version 1.4.1 includes 2 new features:
[Auto-detect Formatting](https://github.com/bitst0rm-pub/Formatter#auto-detect-formatting)
[Per-project Formatting](https://github.com/bitst0rm-pub/Formatter#per-project-formatting)
so you can now use `.sublime-project`
Just info, best regards

**Comment by asparc** [comment]
Oh, I like this! Especially the per-project formatting I find useful! Thanks :-)
