### ISSUE TITLE
No format options

### ISSUE THREAD

**Issue by MochyPei** [bitst0rm-pub/Formatter#52]
When i tried to find Formatter in packages through Sublime Text, i can't find it, so, i downloaded it from here, and unpacked and renamed folder. In sublime it's appears, but in Formatter tab, it's only button "Quick Options" that's not doing anything.

![sublime_text_dOCqedg5sq](https://github.com/bitst0rm-pub/Formatter/assets/50088049/4fa428ed-c741-44b3-a70a-00c0822f65eb)

**Comment by bitst0rm** [comment]
Hi @MochyPei 

This is because the Sublime Text/Packages/User/`Formatter.sublime-settings` is empty and needs to set up on your end.

Preferences > Package Settings > Formatter > Settings
Then you need to pick up settings key from the left to the right pane.
Options are flexible, you do not need to take everything there, just the one you need.
At least one plug-in must be set `"disable": false,` then the menu will get the menu item showed.

In your case User settings would be:
_Formatter.sublime-settings_
```js
{
    "debug": "status",
    "formatters": {
        "svgomax": {
            "info": "https://github.com/svg/svgo",
            "disable": false,  // activate and showing menu item
            "format_on_save": false,
            "new_file_on_format": false,
            "syntaxes": ["svg"],
            "executable_path": ["/path/to/node_modules/.bin/svgo"],
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/svgomax_rc.js"
            }
            /* requires node on PATH if omit interpreter_path */
        }
    }
}
```

I will check to see why Formatter is not showing up on Packages Control so you could not find it to install.

Update: The Formatter package is still online and installable through Packages Control as i see.
Manual download to use will not get auto updates.

<img width="796" alt="screenshot" src="https://github.com/bitst0rm-pub/Formatter/assets/5733550/3fe23c33-9ef4-4d95-b17e-bc0428f68620">

**Comment by jamesguo71** [comment]
curious - why there is no default config?

**Comment by bitst0rm** [comment]
Hi @jamesguo71 

From the README.md:
> The following setting details - along with their default values and examples - are provided to guide you on how to set it up.

So, In the left pane, which is read-only and uneditable for users, all settings are _already_ set to default.

For example:
_Left pane_:
```json
    "show_words_count": {
        "enable": true,
        "use_short_label": false,
        "ignore_whitespace_char": true
    },
```
_Right pane_ (User setting): If you prefer a shorter label, then just write to the right pane with:
```json
    "show_words_count": {
        "use_short_label": true
    },
```

By default, all plugins are disabled. You must copy what you want and set:
`enable: true`

Here is my complete configuration, where I've retained all default settings and only made necessary adjustments::
```json
"debug": "status",
{
        "jsbeautifier": {
            "enable": true,
            "syntaxes": ["js", "css", "html", "json", "tsx", "vue"],
            "executable_path": ["${packages}/User/formatter.assets/javascript/node_modules/.bin/js-beautify"],
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/jsbeautify_rc.json"
            }
}
```
