### ISSUE TITLE
[clang-format] Can you help me solve this problem, I really can't solve it

### ISSUE THREAD

**Issue by LmtITnlv** [bitst0rm-pub/Formatter#54]
![屏幕截图 2024-05-30 211949](https://github.com/bitst0rm-pub/Formatter/assets/119053673/381ac12e-bb60-4896-91a4-0f4e37fc0db4)

**Comment by bitst0rm** [comment]
Hi @LmtITnlv 

It looks like you're using an outdated version of clang-format (clang 13.0.1 or older). The developers changed the `—style` argument over two years ago or more, and Formatter now uses the new `—style` argument accordingly. Please update your clang-format to the newer version.

They changed it here in 2020: https://reviews.llvm.org/D72326
Committed in 2022: https://github.com/llvm/llvm-project/commit/b9e173fcd46b336b5589f577a74de9472d4deae3
Released as 14.0.0-RC1 in 2022

**Comment by LmtITnlv** [comment]
Thank you very much for taking the time to reply to my question, I didn't install the full LLVM after reading the tutorial on the Internet for convenience, I only downloaded the clang-format.exe from LLVM Snapshot Builds, as shown in the picture: 
![屏幕截图 2024-05-31 110030](https://github.com/bitst0rm-pub/Formatter/assets/119053673/8e69e2f5-b1a0-4ade-8dbb-88625cb77207)

next I will go to find the clang-format.exe to download the latest version, in short, thank you very much for your help

**Comment by bitst0rm** [comment]
@LmtITnlv You are welcome.
This repo claims to provide static-linked version of clang-format for download. I did not test it, but I see they have the lastest binary without to install the whole LLVM:
https://github.com/muttleyxd/clang-tools-static-binaries/releases

clang-format-17_windows-amd64.exe | 2.72 MB | ~~Nov 6, 2023~~ Jan 28, 2024 (click `Show all 386 assets`)

---

<sub>They use GitHub workflow to compile on GitHub machines, so the binaries should be clean and safe to use:
https://github.com/muttleyxd/clang-tools-static-binaries/blob/master/.github/workflows/clang-tools-amd64.yml</sub>

<sub>If you fork the repo, then you can trigger the action by yourself and will get all compiled binaries on your Releases page.</sub>

**Comment by LmtITnlv** [comment]
Thank you very much for your enthusiastic response. I have downloaded and installed the LLVM binary files, and then the Formatter has run successfully (since I found it's only 300MB in size, it was quite fast to download). I feel very honored to meet a guru like you.

**Comment by bitst0rm** [comment]
Thank you for your kind words.

Since there is no bug at the application (Formatter) level and everything is working as expected, I recommend switching to `debug: "status"` instead of `debug: true` for daily use. This way, Formatter will only report issues at the 3rd-party plugins level, also only formatting-related issues occurring with your code.

For more convenience, I also recommend using the [auto-detect formatting](https://github.com/bitst0rm-pub/Formatter?tab=readme-ov-file#auto-detect-formatting) feature in your settings, especially if you use various plugins for C, PHP, JavaScript, etc.

For security reasons, I will pin this issue as info so others can download binaries from a safer source.
