### ISSUE TITLE
If I have a json file, terribly formatted, which option will format it?

### ISSUE THREAD

**Issue by rickersilva** [bitst0rm-pub/Formatter#64]
![image](https://github.com/user-attachments/assets/6bf74d33-c260-4991-8814-35f49dd47b6f)

**Comment by bitst0rm** [comment]
Formatter only includes Python's built-in JSON named as `jsonmax` out-of-box. However, this is not the pseudo JSON5, so it cannot process comments.
Otherwise, you will need to install one of the additional plugins: [js-beautifier](https://github.com/beautify-web/js-beautify), [prettier](https://github.com/prettier/prettier), [prettierd](https://github.com/fsouza/prettierd), [prettydiff](https://github.com/prettydiff/prettydiff), [deno](https://github.com/denoland/deno), [topiary](https://github.com/tweag/topiary), [dprint](https://github.com/dprint/dprint), [biome](https://github.com/biomejs/biome) in order to format JSON with Formatter.

Then, activate it in the `Formatter: Settings` (your screenshot):

`"enable": true,`  // This will make it appear in the Menu and the Command Palette.

here for example, jsonmax:
```js
        "jsonmax": {
            "info": "build-in",
            "enable": true,
            "format_on_save": false,
            "format_on_paste": false,
            "new_file_on_format": false,
            "dir_format": false,
            "syntaxes": ["json"],
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/jsonmax_rc.json"
            }
            /* build-in, no executable. json not json5 with comments. */
        },
```

and for jsbeautifier it would be:

```js
        "jsbeautifier": {
            "info": "https://github.com/beautify-web/js-beautify",
            "enable": true,
            "format_on_save": false,
            "format_on_paste": false,
            "new_file_on_format": false,
            "dir_format": false,
            "syntaxes": ["js", "css", "html", "json", "tsx", "vue"],
            "exclude_syntaxes": {
                "html": ["markdown"]
            },
            "executable_path": ["js-beautify"],
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/jsbeautify_rc.json"
            }
            /* requires node on PATH if omit interpreter_path */
        },
```
after that you can control with the `Formatter: Quick Options`
